insert into public.salary_entries (
  country,
  profession_category,
  job_title,
  monthly_salary_usd,
  employment_type,
  experience_level,
  note,
  ip_hash
) values
('United States', 'Software Engineering', 'Backend Engineer', 9200, 'Remote', 'Senior (5-10yr)', 'Series B startup, equity excluded.', md5(random()::text)),
('Germany', 'Software Engineering', 'Full Stack Engineer', 5800, 'Hybrid', 'Mid (2-5yr)', 'Berlin product company.', md5(random()::text)),
('United Kingdom', 'Data / Analytics', 'Data Analyst', 4300, 'Local', 'Mid (2-5yr)', 'Includes annual bonus spread monthly.', md5(random()::text)),
('Canada', 'Design / UX', 'Product Designer', 5100, 'Hybrid', 'Senior (5-10yr)', 'Toronto SaaS.', md5(random()::text)),
('Australia', 'Healthcare / Medical', 'Registered Nurse', 6200, 'Local', 'Senior (5-10yr)', null, md5(random()::text)),
('Netherlands', 'Product Management', 'Product Manager', 6700, 'Hybrid', 'Senior (5-10yr)', null, md5(random()::text)),
('France', 'Marketing / Growth', 'Growth Marketer', 3900, 'Hybrid', 'Mid (2-5yr)', null, md5(random()::text)),
('Spain', 'Sales', 'Account Executive', 4100, 'Local', 'Mid (2-5yr)', 'OTE not included.', md5(random()::text)),
('Portugal', 'Customer Support', 'Support Specialist', 2100, 'Remote', 'Junior (0-2yr)', null, md5(random()::text)),
('Poland', 'Finance / Accounting', 'Financial Analyst', 3200, 'Hybrid', 'Mid (2-5yr)', null, md5(random()::text)),
('United Arab Emirates', 'Legal', 'Corporate Counsel', 9800, 'Local', 'Lead/Principal (10yr+)', null, md5(random()::text)),
('Singapore', 'Consulting', 'Strategy Consultant', 8800, 'Local', 'Senior (5-10yr)', null, md5(random()::text)),
('India', 'Software Engineering', 'Frontend Engineer', 2500, 'Remote', 'Mid (2-5yr)', 'US company payroll through EOR.', md5(random()::text)),
('Brazil', 'Operations / Management', 'Operations Manager', 3000, 'Hybrid', 'Senior (5-10yr)', null, md5(random()::text)),
('Mexico', 'Content / Writing', 'Content Strategist', 2400, 'Remote', 'Mid (2-5yr)', null, md5(random()::text)),
('Japan', 'Education / Teaching', 'International School Teacher', 4700, 'Local', 'Senior (5-10yr)', null, md5(random()::text)),
('South Korea', 'Product Management', 'Associate Product Manager', 3600, 'Local', 'Junior (0-2yr)', null, md5(random()::text)),
('Switzerland', 'Finance / Accounting', 'Senior Accountant', 7600, 'Hybrid', 'Senior (5-10yr)', null, md5(random()::text)),
('Sweden', 'Software Engineering', 'DevOps Engineer', 6400, 'Hybrid', 'Senior (5-10yr)', null, md5(random()::text)),
('Norway', 'Construction / Engineering', 'Civil Engineer', 7000, 'Local', 'Senior (5-10yr)', null, md5(random()::text)),
('Saudi Arabia', 'Real Estate', 'Property Manager', 5200, 'Local', 'Mid (2-5yr)', null, md5(random()::text)),
('South Africa', 'Hospitality / Tourism', 'Hotel Manager', 2900, 'Local', 'Senior (5-10yr)', null, md5(random()::text)),
('Turkey', 'Sales', 'Regional Sales Manager', 3400, 'Hybrid', 'Senior (5-10yr)', null, md5(random()::text)),
('Thailand', 'Marketing / Growth', 'Performance Marketer', 2600, 'Remote', 'Mid (2-5yr)', null, md5(random()::text)),
('Vietnam', 'Software Engineering', 'Mobile Developer', 2800, 'Hybrid', 'Mid (2-5yr)', null, md5(random()::text)),
('Indonesia', 'Operations / Management', 'Supply Chain Analyst', 2200, 'Local', 'Mid (2-5yr)', null, md5(random()::text)),
('Philippines', 'Customer Support', 'Customer Success Manager', 2300, 'Remote', 'Mid (2-5yr)', null, md5(random()::text)),
('Ireland', 'Data / Analytics', 'Business Intelligence Engineer', 5600, 'Hybrid', 'Senior (5-10yr)', null, md5(random()::text)),
('New Zealand', 'Education / Teaching', 'STEM Teacher', 4200, 'Local', 'Mid (2-5yr)', null, md5(random()::text)),
('Argentina', 'Other', 'Freelance Translator', 1800, 'Remote', 'Junior (0-2yr)', null, md5(random()::text));
