/**
 * Below this many real submissions, a /:country/:profession page has no
 * substantive unique content (just an empty template) and should not be
 * indexed or listed in the sitemap. ~1,960 country×profession URLs exist
 * combinatorially (118 countries × 18 professions) but only a fraction have
 * enough real data to be worth Google's attention — submitting all of them
 * regardless of data volume is what produced ~1,900 GSC "Discovered –
 * currently not indexed" pages in September 2026. See generateMetadata in
 * app/[country]/[profession]/page.tsx (noindex below threshold) and
 * app/sitemap.ts (excluded from sitemap below threshold).
 */
export const MIN_SUBMISSIONS_FOR_INDEX = 5;

export const PROFESSION_CATEGORIES = [
  "Software Engineering",
  "Design / UX",
  "Marketing / Growth",
  "Sales",
  "Finance / Accounting",
  "Legal",
  "Healthcare / Medical",
  "Education / Teaching",
  "Operations / Management",
  "Customer Support",
  "Data / Analytics",
  "Product Management",
  "Content / Writing",
  "Consulting",
  "Real Estate",
  "Construction / Engineering",
  "Hospitality / Tourism",
  "Other",
] as const;

export const EXPERIENCE_LEVELS = [
  "Junior (0-2yr)",
  "Mid (2-5yr)",
  "Senior (5-10yr)",
  "Lead/Principal (10yr+)",
] as const;

export const EMPLOYMENT_TYPES = ["Remote", "Local", "Hybrid"] as const;
export const SALARY_TYPES = ["gross", "net"] as const;

/** Same alphabetical list as VisaPulse (`visapulse/lib/constants.ts`). */
export const COUNTRIES = [
  "Albania",
  "Algeria",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Bolivia",
  "Bosnia",
  "Brazil",
  "Cambodia",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Czech Republic",
  "Denmark",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Guatemala",
  "Honduras",
  "Hungary",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Lebanon",
  "Libya",
  "Malaysia",
  "Mexico",
  "Netherlands",
  "Morocco",
  "Moldova",
  "Montenegro",
  "Myanmar",
  "Nepal",
  "New Zealand",
  "Nicaragua",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Rwanda",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Tanzania",
  "Thailand",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vietnam",
] as const;
