export const PROFESSION_CATEGORIES = [
  "Software Engineering",
  "Design / UX",
  "Marketing / Growth",
  "Sales",
  "Finance / Accounting",
  "Legal",
  "Healthcare / Medical",
  "Education / Teaching",
  "Operations / Management",
  "Customer Support",
  "Data / Analytics",
  "Product Management",
  "Content / Writing",
  "Consulting",
  "Real Estate",
  "Construction / Engineering",
  "Hospitality / Tourism",
  "Other",
] as const;

export const EXPERIENCE_LEVELS = [
  "Junior (0-2yr)",
  "Mid (2-5yr)",
  "Senior (5-10yr)",
  "Lead/Principal (10yr+)",
] as const;

export const EMPLOYMENT_TYPES = ["Remote", "Local", "Hybrid"] as const;

export const COUNTRIES = [
  "Argentina",
  "Australia",
  "Austria",
  "Belgium",
  "Brazil",
  "Bulgaria",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Croatia",
  "Czech Republic",
  "Denmark",
  "Egypt",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hong Kong",
  "Hungary",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Kenya",
  "Malaysia",
  "Mexico",
  "Morocco",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Romania",
  "Saudi Arabia",
  "Serbia",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sweden",
  "Switzerland",
  "Thailand",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Vietnam",
] as const;
